# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
  #  <title>Jeanne Yu</title>
   # <meta name="description" content="Hello! I am the first-year PhD student in the Department of Linguistics at Rutgers University. I received my MA in General Linguistics from the University of...">
    #<link rel="canonical" href="/">
  

  #<script>
   # /* Cut the mustard */
    #if ( 'querySelector' in document && 'addEventListener' in window ) {
     # document.documentElement.className = document.documentElement.className.replace(/\bno-js\b/g, '') + 'js';
    #}
 # </script>

  #<link rel="stylesheet" href="/assets/css/main.css">
  #<link rel="stylesheet" href="/assets/css/skins/default.css">
  #<link rel="alternate" type="application/atom+xml" title="Jeanne Yu" href="/feed.xml">




 title: Jiaxing Jeanne Yu 
 email: jiaxing.j.yu@rutgers.edu
 description: >- # this means to ignore newlines until "baseurl:"
  Hello! I am the first-year PhD student in the Department of Linguistics at Rutgers University.<br/> I received my MA in General Linguistics from the University of Rochester in 2020 and BA in Chinese Literature and Languages from Nanjing University in 2018.
   <style>
p.site-description.animated.fadeIn {
     font-size: 15px;
     font-style: normal;
     font-family: 'Source Sans Pro', sans-serif;
     text-align: justify;
     max-width: 800px;
     margin: auto;
   }
  </style>
 baseurl: "" # the subpath of your site, e.g. /blog
 url: "" # the base hostname & protocol for your site, e.g. http://example.com
 twitter_username: jekyllrb
 github_username:  jekyll

 Build settings
 remote_theme: "mmistakes/so-simple-theme@3.2.0"
 plugins:
   - jekyll-feed
  
 # <description="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,400i,700,700i|Lora:400,400i,700,700i">

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

