# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Jiaxing Jeanne Yu 
email: jiaxing.j.yu@rutgers.edu
description: >- # this means to ignore newlines until "baseurl:"
  Hello! I am the first-year PhD student in the Department of Linguistics at Rutgers University.<br/> I received my MA in General Linguistics from the University of Rochester in 2020 and BA in Chinese Literature and Languages from Nanjing University in 2018.
#   <style>
# p.site-description.animated.fadeIn {
#     font-size: 15px;
#     font-style: normal;
#     font-family: 'Source Sans Pro', sans-serif;
#     text-align: justify;
#     max-width: 800px;
#     margin: auto;
# }
# </style>
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
remote_theme: "mmistakes/so-simple-theme@3.2.0"
plugins:
  - jekyll-feed
  
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,400i,700,700i|Lora:400,400i,700,700i">

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
theme: jekyll-theme-so-simple
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"



google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname: # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: mmistakes # site's Twitter username

# Liquid
liquid:
  error_mode: strict

# Build settings
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: false

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
  # Recipe defaults
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: post
      comments: true
      share: true

# Site Author
author:
  name: Michael Rose
  picture: /images/michael-rose-photo.jpg
  email:
  twitter: mmistakes
  links:
    - title: Twitter
      url: https://twitter.com/mmistakes
      icon: fab fa-twitter-square
    - title: Instagram
      url: https://instagram.com/mmistakes
      icon: fab fa-instagram
    - title: GitHub
      url: https://github.com/mmistakes
      icon: fab fa-github-square

# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/mmistakes
    icon: fab fa-twitter-square
  - title: Instagram
    url: https://instagram.com/mmistakes
    icon: fab fa-instagram
  - title: GitHub
    url: https://github.com/mmistakes
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square